# Generated by Django 4.2 on 2024-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('profile', models.ImageField(upload_to='directors/')),
                ('twitter', models.URLField(max_length=100)),
                ('facebook', models.URLField(max_length=100)),
                ('linkedin', models.URLField(max_length=100)),
            ],
        ),
    ]
