# Generated by Django 4.2 on 2024-10-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Page', '0002_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
