# Generated by Django 4.2 on 2024-10-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About_Page', '0003_alter_director_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='page_Title',
        ),
    ]
