# Generated by Django 4.2 on 2024-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Page', '0004_remove_info_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_Image',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='about_Image2',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
    ]
