# Generated by Django 4.2 on 2024-05-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News_Page', '0002_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsGallery/')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Page.news')),
            ],
        ),
    ]
