# Generated by Django 4.2 on 2024-05-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News_Page', '0004_newsgallery_photoname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsgallery',
            name='image',
        ),
        migrations.AddField(
            model_name='newsgallery',
            name='photoCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News_Page.news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsgallery',
            name='photo',
            field=models.ImageField(upload_to='newsGallery/'),
        ),
    ]
