# Generated by Django 4.2 on 2024-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_Link', models.URLField()),
                ('logo', models.ImageField(upload_to='brand/')),
            ],
        ),
    ]
