# Generated by Django 4.2 on 2024-10-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0008_category_brand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
