# Generated by Django 4.2 on 2024-10-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0010_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
