# Generated by Django 4.2 on 2024-10-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0013_rename_share_link_product_shop_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop_Link',
        ),
    ]
