# Generated by Django 4.2 on 2024-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0016_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='background',
            field=models.ImageField(default=1, upload_to='brand/'),
            preserve_default=False,
        ),
    ]
